### ISSUE TITLE
Web and Desktop support.

### ISSUE THREAD

**Issue by sarankumar-ns** [chargebee/chargebee-flutter#17]
Hi,
Please add support for Other Platforms including Web and Desktop.

I hope It can be done if this package was built entirely in Dart from scratch instead of platform SDK dependent.

As of now the option to check subscription status can be added.

**Comment by cb-amutha** [comment]
@sarankumar-ns Sorry for the late reply here. Could you please use Chargebee js library [link](https://www.chargebee.com/checkout-portal-docs/components-fields-integrations.html#setting-up-chargebee-js) and API's for the web and desktop platform if needed. Let us know if any more help on this. Thanks.
