### ISSUE TITLE
No inline documentation

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-flutter#37]
#### Example:
What does `retrieveSubscriptions()` do? Why does it take an untyped `Map queryParams` instead of actual argument names?

Sure, I could look in the readme, but it would be much faster if I could rely on code editor suggestions and inline documentation like with every other package. This also goes beyond just having the untyped map parameter documented. This sdk could easily hide that implementation detail of the underlying native sdks (which imo shouldn't expose this detail either).

#### There's a reason why this gives you a higher score on pub.dev. It's useful!
<img width="791" alt="Bildschirm­foto 2023-01-21 um 19 36 44" src="https://user-images.githubusercontent.com/16866223/213882098-2eca846d-4178-4db4-8e76-8c579429d070.png">

**Comment by sarankumar-ns** [comment]
I also felt the same. It looks like the documentation was written in a block comment.
![image](https://user-images.githubusercontent.com/33630797/221470111-cae7b03c-c5d8-49bc-b1f0-dee462a4865d.png)

But darts preferred method is either `///` or `/**...*/`.
![image](https://user-images.githubusercontent.com/33630797/221470337-30ba0068-9e0f-4028-b76d-bf333b7136a4.png)

**Comment by ciriousjoker** [comment]
I think `/** */` is just supported to make it compatible with jsdoc, but in reality every package ever uses `///` and the linter will probably scream at you if you try anything else.

**Comment by sarankumar-ns** [comment]
> I think `/** */` is just supported to make it compatible with jsdoc, but in reality every package ever uses `///` and the linter will probably scream at you if you try anything else.

Yes.

**Comment by cb-amutha** [comment]
@ciriousjoker and @sarankumar-ns , Agree with the above comments and We have updated the API documents accordingly  on the latest release. hence closing this issue. Thanks
