### ISSUE TITLE
`Product` is lacking information

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-flutter#39]
#### `Product.price` should be a number

Right now, it's a string for seemingly no reason, since currency isn't included. Also, this is necessary to do calculations like "less than x per week!" or display the formatting correctly, e.g. "12.34" in the US and "12,34" in Germany.

#### `Product.currency` is missing

- Would be fixed by #43

#### `Product.duration` is missing

We need to display the pricing as "x USD / y months".

a) because it makes sense and
b) to satisfy store guidelines.

Our workaround is to hardcode this information in the app, but obviously it would be better if this was automatically provided.

**Comment by cb-amutha** [comment]
The product price being returned as string(something like $3,000.00) in Android Sku details that’s why price made it as string in Product class. could able to convert string into required types in application level? If not, will have to make change the Product.price to number. Please confirm.

Product.duration - accepted the points. will be adding the subscriptionPeriod in Product. eg. **[Product(id: chargebee.pro.ios, price: 9.99, title: Pro Plan, currencyCode: USD, subscriptionPeriod: 1 year)]**.  Thanks.

**Comment by ciriousjoker** [comment]
Our current solution for the price:
- try to convert to double
- if it throws, display the string as-is
- if it works, format currency according to the user's locale and region

It does work but it's less clean and it still only allows is to do calculations _some_ of the time. The native stores already provide this info as a number, why not provide both through this sdk?

---

Please don't make `subscriptionPeriod` a string like this seems. Dart has a great `Duration` type. If it was a duration, then we could write `subscriptionPeriod.inMonths` and get a number. Otherwise, please split the unit (month/year) from the actual number, again to give much more flexibility related to how we want to display that information.

**Comment by cb-amutha** [comment]
Ok, same splitting the subscription unit from actual number and it provides the exact duration which has configured on the App Store subscriptions. Below are the code snippets added as extension function in SKProduct

func subscriptionDuration() -> String {
        let period:String = {
            switch self.subscriptionPeriod?.unit {
            case .day: return "day"
            case .week: return "week"
            case .month: return "month"
            case .year: return "year"
            case .none: return ""
            case .some(_): return ""
            }
        }()
        let numOfUnits = self.subscriptionPeriod?.numberOfUnits ?? 0
        let pluralInPeriod = numOfUnits > 1 ? "s" : ""
        return String(format: "%d %@%@", arguments: [numOfUnits, period, pluralInPeriod])
    }

**Comment by ciriousjoker** [comment]
Not quite sure what you mean by your comment.

Will we be able to do something like this in the future?

```dart
String type = product.durationType:
int length = product.durationLength?
```

Even better if we could do this:
```dart
final months = product.duration.inMonths;
```

For the second solution to work, `product.duration` needs to be of the `Duration()` type in Dart.
