### ISSUE TITLE
Difficult error handling

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-flutter#40]
#### Example errors

| cancelled | configure() not called |
|-|-|
| <img width="541" alt="Bildschirm­foto 2023-01-21 um 16 56 29" src="https://user-images.githubusercontent.com/16866223/213875255-f774fd85-7360-469c-a5bf-be92a596a069.png"> | <img width="540" alt="Bildschirm­foto 2023-01-21 um 19 47 01" src="https://user-images.githubusercontent.com/16866223/213882428-9451cc1c-1106-4fdf-a300-14ce1ba30825.png"> |

Error code `"null"` for everything, are you kidding me?

#### Example errors

| cancelled | on a simulator (not chargebee's fault) |
|-|-|
| <img width="535" alt="Bildschirm­foto 2023-01-21 um 21 11 41" src="https://user-images.githubusercontent.com/16866223/213885397-45a0614c-fc56-4487-bda4-343c8e110344.png"> | <img width="539" alt="Bildschirm­foto 2023-01-21 um 21 18 00" src="https://user-images.githubusercontent.com/16866223/213885636-11002b42-d45c-4ae1-ad4c-f62abde30cb3.png"> |

On Android, details is a dynamic and apparently contains a stringified stacktrace. On iOS, we get a useless `message` property instead and need to use `details` to figure out what happened.

## The necessary, ugly workaround

We can't display the English, internal(!) error message to the end user and now we seriously need to check if the error message contains specific words to hopefully distinguish them!?

Here's our "solution", but please just provide error codes instead...

```dart
try {
  return await Chargebee.purchaseProduct(product, uid);
} on PlatformException catch (e) {
  // On Android, message will be set (details is a stringified stacktrace)
  if (e.message != null) {
    // Android: "User pressed back or canceled a dialog" <- no, not a typo, just USA...
    if (e.message!.contains("canceled")) return PurchaseResult("", "", PurchaseResultExtension.kCancelled);
  }

  // On iOS, details will be set instead.
  if (e.details != null) {
    // iOS: "User cancelled the payment."
    if (e.details.toString().contains("cancelled")) {
      return PurchaseResult("", "", PurchaseResultExtension.kCancelled);
    }
  }

  // List of known error messages at the time of writing:
  // Android:
  // - "User pressed back or canceled a dialog"
  // - "SDK key not available to proceed purchase"
  // iOS:
  // - "User cancelled the payment."
  // - "Purchase is unavailable due to unknown or unexpected reason. Please try again later."

  return PurchaseResult("", "", PurchaseResultExtension.kError);
}
```

## An actual solution

Please provide useful PlatformExceptions with actual error codes that match(!) between Android and iOS.

**Comment by cb-amutha** [comment]
@ciriousjoker Sure, Working on it.
