### ISSUE TITLE
configure() never returns

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-flutter#41]
- Same issue as here: #23
- The call back is never called. I tested it on iOS and Android.
- retrieveProducts() works, so I assume that configure() also does

This is in the logs:

> Note: pre-requisites configuration is mandatory for SDK to work. Learn more(https://www.chargebee.com/docs/2.0/mobile-app-store-product-iap.html)

Is this normal? If I remember correctly it is, but I'm not sure.

**Comment by ciriousjoker** [comment]
Probably related:
- https://github.com/chargebee/chargebee-android/issues/32

**Comment by cb-amutha** [comment]
Hi @ciriousjoker 
This is normal flow of configuration method. It doesn’t provide the callbacks, just verify app details with Chargebee. is there any specific reason looking out for the callback?

**Comment by ciriousjoker** [comment]
I'm trying to use it like this:

```dart
try {
  await configure();
  // Log if it worked
} catch (e) {
  ...
}
```

Currently, it seems like it will throw and if it doesn't throw, that means everything went smoothly?

What if the user has no internet connection? In that case it failed silently because the network request never completes.

**Comment by cb-amutha** [comment]
In Android, if no internet connection it should throw error, this use case has been handled. can you please check and confirm?. for iOS, will update the sdk to handle this scenario. Thanks.

**Comment by ciriousjoker** [comment]
During my testing, it did throw an error, but network requests are really hard. Sometimes there is a working wifi connection or 3G connection, but due to high package loss the bytes basically come in one by one. Is there a timeout for such cases at which point the request is considered "failed"?

**Comment by cb-amutha** [comment]
> In Android, if no internet connection it should throw error, this use case has been handled. can you please check and confirm?. for iOS, will update the sdk to handle this scenario. Thanks.

We have updated the sdk that throws an error in case of failure during configure() method in both iOS and Android. Please check and let us know if running into issue around this method. Thanks.
