### ISSUE TITLE
PurchaseResult contains weird data

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-flutter#42]
<img width="391" alt="Bildschirm­foto 2023-01-21 um 22 32 57" src="https://user-images.githubusercontent.com/16866223/213887883-a1780b75-e886-441e-a38d-ca394bf383cf.png">

1. Why is `status: "true"`?? After reading the README, I was under the impression that this field is supposed to match the possible Chargebee subscription status values (active, trial, non renewing etc.)
2. Why is the planId & subscriptionId `"Optional(...)"`?? Looks like some sort of serialization error of Swift's `Optional` type

**Context:** I'm on iOS.

**Comment by cb-amutha** [comment]
@ciriousjoker **PurchaseResult.status** - We are setting up the status in sdk level which to indicate product purchase done success/failed, this is not related to backend subscription status(ACTIVE, trial etc). And on point 2, ideally planId & subscriptionId shouldn't be an optional let's check and update accordingly.
