### ISSUE TITLE
_CastError on Price in Product Model for integer value prices. Chargebee.retrieveProducts fails. 

### ISSUE THREAD

**Issue by DylanCross** [chargebee/chargebee-flutter#54]
For iOS subscription plans with integer value prices: ie $5 / per month, retrieveProducts fails due to a _CastError in the Product.fromJson method. The method uses type double for product price and the cast of an int to a double fails. 

This issue can be mitigated by changed the type of Product.price from double to num. 
a. Change the delcared type of price from double to num, line 8 of the file product.dart. 
b. Change the cast from json['productPrice'] as double to json['productPrice'] as num in Product.fromJson, line 19 of the file product.dart. 

This issue was introduced in version 0.0.10 with the type change of Product.price from String to double.

**Comment by cb-amutha** [comment]
Hi @DylanCross , thanks for reporting issue here. 
If you want to display the price as String, could you use Product.priceString. ref link - https://github.com/chargebee/chargebee-flutter/blob/main/lib/src/utils/product.dart#L9. try this out and let us know still facing an issue. Thanks.

**Comment by DylanCross** [comment]
That doesn't work. The retrieveProducts function errors, and no Product object is returned to even pull the Product.priceString from. 

Here is a sample product: {productPriceString: 200, productId: standard1_hebrew_annually_1, subscriptionPeriod: {numberOfUnits: 1, periodUnit: year}, productPrice: 200, productTitle: Learner Plan - Hebrew (1yr.), currencyCode: USD}

As you can see, the productPrice is an integer, which flutter won't cast to double. I changed the data type to num in the Product class, and now it works for me. 

To reporduce, try creating a plan in the apple app store with a whole dollar price: ie $5.00, not $4.99. The plan price will in the JSON object from apple will be 5, which will error on the type cast when parsing the JSON.

**Comment by craigspicer** [comment]
Same issue on iOS. I am able to fix by using num instead of double for productPrice by editing product.dart in the Chargebee SDK. This is in the latest version 0.0.11.
