### ISSUE TITLE
Works in Debug mode, doesn't work in Release mode

### ISSUE THREAD

**Issue by timeshift-ted** [chargebee/chargebee-flutter#70]
Everything has been working well while testing in Debug mode on my Android phone.

However, as soon as I tried compiling in Release mode (using live Chargebee site) it hangs forever on the configure() step and never moves from there. No error, just hangs forever.

Here is a code snippet, which is in a try {} block.

`await Chargebee.configure(
          globals.chargebeeSiteName, globals.chargebeePublishableAPIKey,
          globals.chargebeeIOSSDKKey, globals.chargebeeAndroidSDKKey)`

Same code and same exact variables work in Debug mode and not in Release mode. Everything else on the app works in Release mode, no problems with Internet permissions, just Chargebee Flutter hangs up.

**Comment by cb-haripriyan** [comment]
Thanks @timeshift-ted 
Could you add the rule below in proguard file and please test it out?
`-keep class com.chargebee.android.** { *;}`

We would be updating this as part of our SDK in the upcoming releases.

**Comment by timeshift-ted** [comment]
Hi,

As mentioned, we do not use proguard, this have no proguard file.

Ted Johnson
Timeshift Media, Inc.

**Comment by cb-amutha** [comment]
Hi @timeshift-ted,
The fixes added in the latest version [v0.2.1](https://pub.dev/packages/chargebee_flutter) and it handles proGuard sdk level.
app doesn't required to be configured proGuard. Please use the latest version and confirm if still issues in release mode.
Thanks.
