### ISSUE TITLE
Google Play Billing Library outdated

### ISSUE THREAD

**Issue by craigspicer** [chargebee/chargebee-flutter#77]
<img width="930" alt="Screenshot 2023-11-08 at 22 37 32" src="https://github.com/chargebee/chargebee-flutter/assets/50133340/7cc9b5bd-c073-498d-ae16-d0b036d752c5">

I am unable to submit an update to Google Play as the Flutter plugin is using an outdated version of the Google Play Billing Library. I am on the latest version of the plugin (0.3.0).

Please resolve this urgently.

**Comment by cb-haripriyan** [comment]
Hi @craigspicer 
This is currently our top priority and will be shipping the upgraded SDK in the upcoming days.

**Comment by cb-haripriyan** [comment]
@craigspicer The release https://github.com/chargebee/chargebee-flutter/releases/tag/v0.4.0 upgrades the underlying Billing Library version to 5.2.1. Can you verify if that unblocks you?

**Comment by cb-haripriyan** [comment]
Thanks for confirming. Do note that we would be shipping new SDKs which adds support for the Billing Library 5 features along with migration guide.
