### ISSUE TITLE
Products not found

### ISSUE THREAD

**Issue by jjclinton** [chargebee/chargebee-flutter#85]
On iOS

retrieveProductIdentifiers works, but retrieveProducts gives products not found exceptions.

My code:
```
...print("Start payment");

    final resultp = await Chargebee.retrieveProductIdentifiers();
  print("Resultp");
  print(resultp);
  List<Product> products = await Chargebee.retrieveProducts(resultp);...
```

My logs:
// flutter: Start payment
// flutter: Resultp
// flutter: [2A, 1B]
// [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(8, Products not found., Request failed, null)

Am I missing something here?
The API seems to be working since the retrieveProductIdentifiersis getting the correct products IDs, these are the IDs I expect to get from the API ([2A, 1B]).

Also the docs say 
  List<Product> products = await Chargebee.retrieveProducts({productList: "[Product ID's from Google or Apple]"});
But this doesn't work, because the parameter of retrieveProducts is just List<String> productIDs.

**Comment by samarthagarwal** [comment]
I am running into the same issue. 
```
Error Message: Products not found., Error Details: Request failed, Error Code: 8
```

**Comment by jjclinton** [comment]
Issue resolved, reason was that we didn't accept Apple's payment agreements yet. Check out https://developer.apple.com/documentation/storekit/in-app_purchase/testing_in-app_purchases_with_sandbox

It says:
Your Apple Developer Program account is active. For more information, see [What you need to enroll](https://developer.apple.com/programs/enroll/).

Your membership Account Holder has signed the Paid Applications Agreement, as described in [Sign and update agreements](https://developer.apple.com/help/app-store-connect/manage-agreements/sign-and-update-agreements).

You set up the product information in App Store Connect for the app you’re testing. At minimum, set up a product reference name, product ID, a localized name, and a price.

You’re running a development-signed build of your app. Production-signed builds use the production environment.

If you’re testing on iOS, watchOS, or visionOS devices, grant permission for locally installed apps to run on the device. For more information, see [Enabling Developer Mode on a device](https://developer.apple.com/documentation/xcode/enabling-developer-mode-on-a-device).


Follow all of the above steps and it should work!

**Comment by samarthagarwal** [comment]
@jjclinton are you in-app subscriptions on the App Store already submitted for review and approved by Apple?

**Comment by cb-haripriyan** [comment]
Thanks for confirming @jjclinton 

For the reference of anyone who might come across this issue in future, here is the list of things that we need to verify in these cases.

If there are any issues when retrieving IAP Products from Apple store, verify the following details in AppStore Connect:
- The Finance (and other agreements) are accepted in Appstore Connect and the status should show active for your apps.
- App Bundle ID matches with the Bundle ID in App Store Connect.
- Changing the reference name in App Store Connect can also cause products to not fetch on iOS. Create a new product with a different identifier, fill out any missing metadata, and attempt to fetch products again.
- Localizations are set and accepted for the products.
- The ProductId in Appstore Connect should match with the ProductId we are trying to retrieve.
- Enable "In-App Purchase" in Xcode "Capabilities" and in Apple Developer -> "App ID" setting.
