### ISSUE TITLE
Card Tokenization

### ISSUE THREAD

**Issue by JoshanTandukar** [chargebee/chargebee-flutter#86]
Urgent : As of the context, I am not able to see the card tokenization method. Is it in pipeline?

**Comment by cb-haripriyan** [comment]
Hi @JoshanTandukar 
Our Flutter / React Native SDKs are developed to support the in-app payment methods of apple & google. So we don’t support the credit card tokenisation as part of these SDKs.

**Comment by JoshanTandukar** [comment]
It is available in the native SDK. So i am assuming it wont be available in the future as well?

**Comment by cb-haripriyan** [comment]
@JoshanTandukar These are part of the native SDKs, and right now we do not have plan to include them for the hybrid ones.
