### ISSUE TITLE
 App must use Google Play Billing Library version 6.0.1 or later

### ISSUE THREAD

**Issue by ciriousjoker** [chargebee/chargebee-flutter#97]
### Status
You won't be able to release app updates (59 days away)
### Date sent
Jul 1, 2024
### Deadline
Aug 31, 2024
### Violation
App must use Google Play Billing Library version 6.0.1 or later
### Details
To provide users with a safe and secure experience, all apps are required to meet Google Play Billing Library requirements.
Your app uses an old version of Google Play Billing Library. From Aug 31, 2024, all apps must use version 6.0.1 or later.

> Update to a newer version by this date to prevent your updates from being rejected.

---

Please update the Billing Library version soon.

**Comment by ciriousjoker** [comment]
Closing this for now, it seems like I was too quick to report this. The mentioned app bundles are old and new ones aren't flagged anymore.

**Comment by victorcatn** [comment]
I'm having this issue with the latest chagebee-flutter version
